
services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  server:
    build:
      context: .
    container_name: sharedbox-backend
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      - mongo

volumes:
  mongo_data: